### ISSUE TITLE
Split with new files

### ISSUE THREAD

**Issue by ajardin** [symplify/monorepo-split-github-action#13]
Hello and thanks for your amazing work (@rectorphp user here)! :wink:

From what I understand, the split only works with existing files on both sides. If I add a new file, the split does nothing (`[NOTE] No files to change` instead of `[NOTE] Adding git commit`). Is it possible to _force_ the indexation of new changes? 

I assume it's related to [this line](https://github.com/symplify/monorepo-split-github-action/blob/main/entrypoint.php#L82), but I wanted your point of view before submitting any changes.

**Comment by TomasVotruba** [comment]
Hi, thanks for reaching out :)

The split works on existing file on the split repository. 
New files are split too :)

**Comment by ajardin** [comment]
Thanks for your quick response!

Basically, I have a repository where I store all my Docker images and I want to split it to take advantage of the build on Docker Hub instead of GitHub Actions.


Here are some logs with an empty repository.
```
[NOTE] Starting...



[NOTE] Cloning "https://github.com/origamiphp/docker-blackfire-entrypoint.git" repository to "/tmp/monorepo_split/clone_directory" directory



[NOTE] Running: git clone -- https://***@github.com/origamiphp/docker-blackfire-entrypoint.git /tmp/monorepo_split/clone_directory

Cloning into '/tmp/monorepo_split/clone_directory'...
warning: You appear to have cloned an empty repository.


[NOTE] Cleaning destination repository of old files



[NOTE] Copying contents to git repo of 'main' branch

fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.

Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

[NOTE] Files that will be pushed

total 28
drwxr-xr-x 3 1001  121 4096 Jun 15 22:11 .
drwxr-xr-x 3 root root 4096 Jun 15 22:11 ..
drwxr-xr-x 7 root root 4096 Jun 15 22:11 .git
-rw-r--r-- 1 1001  121  436 Jun 15 22:11 Dockerfile
-rw-r--r-- 1 1001  121 1086 Jun 15 22:11 LICENSE
-rw-r--r-- 1 1001  121  585 Jun 15 22:11 README.md
-rw-r--r-- 1 1001  121 1010 Jun 15 22:11 entrypoint.sh

[NOTE] Changing directory from "/github/workspace" to "/tmp/monorepo_split/build_directory"

On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	Dockerfile
	LICENSE
	README.md
	entrypoint.sh

nothing added to commit but untracked files present (use "git add" to track)

[NOTE] No files to change



[NOTE] Changing directory from "/tmp/monorepo_split/build_directory" to "/github/workspace"
```

Here are some logs with an already initialised repository.
```
[NOTE] Starting...



[NOTE] Cloning "https://github.com/origamiphp/docker-blackfire-entrypoint.git" repository to "/tmp/monorepo_split/clone_directory" directory



[NOTE] Running: git clone -- https://***@github.com/origamiphp/docker-blackfire-entrypoint.git /tmp/monorepo_split/clone_directory

Cloning into '/tmp/monorepo_split/clone_directory'...


[NOTE] Cleaning destination repository of old files



[NOTE] Copying contents to git repo of 'main' branch



[NOTE] Files that will be pushed

total 28
drwxr-xr-x 3 1001  121 4096 Jun 15 22:18 .
drwxr-xr-x 3 root root 4096 Jun 15 22:18 ..
drwxr-xr-x 8 root root 4096 Jun 15 22:18 .git
-rw-r--r-- 1 1001  121  436 Jun 15 22:18 Dockerfile
-rw-r--r-- 1 1001  121 1086 Jun 15 22:18 LICENSE
-rw-r--r-- 1 1001  121  585 Jun 15 22:18 README.md
-rw-r--r-- 1 1001  121 1010 Jun 15 22:18 entrypoint.sh

[NOTE] Changing directory from "/github/workspace" to "/tmp/monorepo_split/build_directory"

On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	LICENSE

nothing added to commit but untracked files present (use "git add" to track)

[NOTE] No files to change



[NOTE] Changing directory from "/tmp/monorepo_split/build_directory" to "/github/workspace"
```

In both cases, my "new" files are not pushed to the split repository. But if I update one of the existing files, the split is correctly handled. 😕

**Comment by TomasVotruba** [comment]
I don't have any experience with Docker hub splits, so I can't really help there.
On GitHub Actions splits works well. It might help if the remote branch should exist.

**Comment by TomasVotruba** [comment]
I see, I understand this more clearly now. Thanks :+1: 

Just to verify, the https://github.com/origamiphp/docker-blackfire-entrypoint is complete, but `LICENSE` file is missing?

This is the directory that should be split? https://github.com/origamiphp/docker-images/tree/main/common/blackfire-entrypoint

The GitHub Actions setup seems correct, now sure what is wrong.

**Comment by ajardin** [comment]
Your two assumptions are correct, and I don't understand this either. 🙃 

I will try to take some time today to investigate further.

**Comment by TomasVotruba** [comment]
Just a tip: when I try to debug the split, I usually start with single directory and single file. One can get easily lost if there is over 20 files to work with. Often it's some triviality like wrong directory, slashes path, confused setup directory vs repository in the Github action etc.

It saves me some sleep-less night to create just 1 repository with 1 file in 1 directory and try to split it into 1 remote repository that should contain just 1 file.

**Comment by ajardin** [comment]
I've done some more tests, and I really can't see which error in my setup would cause only changes to existing files to be pushed. So, I tested another approach by looking at the instruction that checks if there are any changes.

I can reproduce the issue locally with raw Git commands only, as you can see in the following snippet. From my point of view, it would be safer to use something like `git status --porcelain` instead of `git diff-index --quiet HEAD`.

What do you think?

```
#!/usr/bin/env bash

# Initialize the local test repository
mkdir -p tests
cd tests
git init --quiet
touch foo.txt
git add foo.txt
git commit --message="Initial commit" --quiet

# Test with an addition of a new file
touch bar.txt
git diff-index --quiet HEAD
echo "Addition exit code = "$?

# Test with a modification to an existing file
echo "Hello world" > foo.txt
git diff-index --quiet HEAD
echo "Modification exit code = "$?

# Remove the local test repository
cd ..
rm -rf tests
```

```
$ bash test.sh
Addition exit code = 0
Modification exit code = 1
```

**Comment by TomasVotruba** [comment]
I have no idea how git works on this level. Basically I've hacked this when needed and try to fix if something is broken :)

Would you suggest to change this in GitHub action? Would it solve your issue?
We can give it a try, then you run the action in dev version to verify. Then we can revert in case of troubles

**Comment by ajardin** [comment]
This change would probably allow the script to handle more cases and solve my issue, but I want to do further testing to ensure there are no side effects. I will send you a pull request if my tests are okay, perhaps tomorrow.

**Comment by ajardin** [comment]
@TomasVotruba It seems to work as expected. 🥳 

I have configured the split of [1 repository](https://github.com/origamiphp/docker-images/blob/main/.github/workflows/images-split.yml) to [10 other repositories](https://github.com/origamiphp?q=Read-only&type=&language=&sort=) with success. My test scenario involved updating one file (`README.md`) with new ones (at least one `Dockerfile`).

Just a small note, because I was afraid I had broken something, we'll have to update the documentation before doing the next release. The names of the inputs have indeed been changed in the meantime ([source](https://github.com/symplify/monorepo-split-github-action/pull/10/files#diff-fab4d7fb461bc6fbe9587f6c03fff98102b1c744145edcf2a993f2ff7cb05a0dL5)). I could prepare the PR if you want.

Thanks again for your work!

**Comment by TomasVotruba** [comment]
Thanks for testing and sharing real repository where I can see the results easily :+1: 

> I could prepare the PR if you want.

That would be great :slightly_smiling_face:
