### ISSUE TITLE
After switching to PHP, the CI run is always successful, even when it should fail

### ISSUE THREAD

**Issue by leoloso** [symplify/monorepo-split-github-action#19]
In this code in `entrypoint.php`:

```php
exec($copyGitDirectoryCommandLine, $outputLines, $exitCode);

if ($exitCode === 1) {
    die('Command failed');
}
```

...the php `die` is only printing the message on screen, but it does not produce an `exit 1`, so the script still does not fail.

Demonstration:

- I created a PR in `leoloso/PoP` to test #18
- There, I'm passing the wrong credentials (https://github.com/leoloso/PoP/blob/465d9d2779781d384cfd0c709faabb4eaf44373b/.github/workflows/split_monorepo.yaml#L20-L22), so doing `git push` will fail
- The code fails, printing the error code (https://github.com/leoloso/PoP/pull/772/checks?check_run_id=2987635297#step:4:80)
- But the run is still successful!

I also tried executing this (https://github.com/leoloso/monorepo-split-github-action/blob/8795fc8/entrypoint.php#L98):

```php
exec('exit ' . $exitCode);
```

But it also doesn't work.

**Comment by leoloso** [comment]
I searched for documentation, but didn't find anything. The GitHub Action docs only explain how to [exit from `entrypoint.sh`](https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions#setting-a-failure-exit-code-in-a-docker-container-action).

So I have no clue how to fix this.

**Comment by Ferror** [comment]
Well there is an official js package..maybe we need something similar - https://github.com/actions/toolkit/tree/main/packages/core

**Comment by TomasVotruba** [comment]
This is rather generic Github Action issue, unrelated to this package.

If you find a better way, please send PR :+1:
