### ISSUE TITLE
`detected dubious ownership in repository`

### ISSUE THREAD

**Issue by danharrin** [symplify/monorepo-split-github-action#36]
It looks like #34 has introduced an issue for us. Since the change was made, our releases have started failing, the action is still marked as successful.

Here's a log from a failed release:

https://github.com/filamentphp/filament/actions/runs/3227856649/jobs/5283553164#step:5:92

The `detected dubious ownership in repository` is never normally reported, and the release still works fine.

I verified that #34 caused the issue by reverting to symplify/github-action-monorepo-split@02755d9ac89929afb8d5aacff142fda76075e507

**Comment by TomasVotruba** [comment]
cc @Ferror

**Comment by andrew-belac** [comment]
We are getting this error using the workflow as described in https://github.com/symplify/symplify/blob/main/.github/workflows/split_monorepo.yaml.  It just started happening within the last week.  

Is there any advice on how to fix this.  The split_monorepo.yaml reference uses v2.0 of the split action.

**Comment by danharrin** [comment]
@andrew-belac when I first encountered this issue, locking this package to `symplify/github-action-monorepo-split@02755d9ac89929afb8d5aacff142fda76075e507` worked.

This morning, I also started experiencing this issue again. I'm still using that same version.

So I think that this time, it's not an issue with Symplify, something has changed in the GitHub actions images overnight. Other reports have also been made - https://github.com/actions/runner-images/issues/6775#issuecomment-1408112981

**Comment by graupnerdemos** [comment]
We just tried using the above mentioned hash in demos-europe/edt and unfortunately the error persists. To my understanding, the change in the GitHub base image is related to changes that [happened in git](https://github.blog/2022-04-12-git-security-vulnerability-announced/) quite a while ago and thus something may have to be done in this action.

**Comment by andrew-belac** [comment]
@TomasVotruba Should we be using the version 2.2, 2.1 or 2.0 of the split action?  The Symplify MonoRepoBuilder references a sample githubaction yaml file that uses 2.0, but the this repo README shows using 2.1 but 2.2. seems to be the most recent release.  I ask because I am wondering if version 2.2 will have the same problem with github ownership. Thank you for any advice in advance.

**Comment by TomasVotruba** [comment]
PRs to fix this are welcomed. I'm out of this game for couple of years so not sure what is the best way.

**Comment by zepfietje** [comment]
Should be fixed by #44.
