### ISSUE TITLE
Job failed: exit code 127

### ISSUE THREAD

**Issue by tiraoui** [symplify/monorepo-split-github-action#37]
It seems after the recent update this error has started to show... code has never been touched in over a year, i have noticed there has been an update on the repo so maybe it has something to do with it!

Error message:

$ apt-get update -y > /dev/null # collapsed multi-line command
/bin/sh: eval: line 125: apt-get: not found
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 127

I am using Ubuntu with gitlab-ci. Any thoughts?

![Screenshot 2022-10-13 at 15 21 43](https://user-images.githubusercontent.com/43049386/195608357-44dc2234-3b3c-487c-8ae5-0778b983a01d.png)

**Comment by tiraoui** [comment]
UPDATE:

it turns out it had to do with my local dns which was preventing the process. :)

**Comment by TomasVotruba** [comment]
Good to know, thanks 👍
