### ISSUE TITLE
Question/Readme: Split without GitHub Actions

### ISSUE THREAD

**Issue by pduersteler** [symplify/monorepo-split-github-action#9]
First of all, thanks to everyone involved working on those tools, really helpful! I hope it is okay to ask a question here since I could not get a clear answer from the readme. The whole monorepo topic is new for me as I used multiple repositores until now, which is problematic in a current project.

As far as I could find out, there was a feature in symplify v8 that allowed to split up the monorepo into multiple repositories. It was removed in v9 (I've read the blog post) and replaced by a github workflow action. Now, I want to set up a mono-repository on a private git server (not on GitHub), which means I can't use the new workflow. What would be the way to go to split the mono-repo into multiple repos on a private git server (e. g. Bitbucket or GitLab)? For starters without a CI that does the whole release, a local command to run as it was possible in v8 would be sufficient. Would you advise to make a custom script for it or is there still something in symplify that would help to achieve this?

**Comment by TomasVotruba** [comment]
Hi, we've put some work into using the Docker image on Gitlab too:
https://github.com/symplify/monorepo-split-github-action/pull/8

Give it a try :+1:
